server:
  port: 8081
example:
  property: I AM DEV
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers:
          - localhost
          zkNodes:
          - localhost
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/ostock_dev
  jpa:
    hibernate:
      ddl-auto: update     
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
    circuitbreakers:
      enabled: true
  
resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        registerHealthIndicator: true 
        ringBufferSizeInClosedState: 5 
        ringBufferSizeInHalfOpenState: 3  
        waitDurationInOpenState: 10s   
        failureRateThreshold: 20
        recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkheadLicenseService:
        maxWaitDuration: 10ms  
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    instances:
      bulkheadLicenseService:
        maxThreadPoolSize: 2   
        coreThreadPoolSize: 2   
        queueCapacity: 2  
        keepAliveDuration: 20ms            
  retry:
    instances:
      retryLicenseService:
        max-attempts: 5
        wait-duration: 10000
        retry-exceptions:
          - java.util.concurrent.TimeoutException
  ratelimiter:
    instances:
      licenseService:
        timeout-duration: 1000ms
        limit-refresh-period: 5000
        limit-for-period: 5        